version: "3.8"
services:
    postgres:
        image: bazel/devops/database:postgres
        volumes:
            - type: volume
              source: db-data
              target: /var/lib/postgresql/data
        environment:
            - "VAULT_USER_PASSWORD=${VAULT_USER_PASSWORD}"
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        ports:
            - "5432:5432"
        networks:
            c3p0:
                ipv4_address: ${POSTGRES_HOST}
    vault:
        image: bazel/devops/vault:vault
        cap_add:
            - IPC_LOCK
        environment:
            - "POSTGRES_HOST=postgres"
            - "VAULT_USER_PASSWORD=${VAULT_USER_PASSWORD}"
        ports:
            - "8200:8200"
        networks:
            c3p0:
                ipv4_address: ${VAULT_HOST}
        depends_on:
            - postgres
    fusionauth:
        image: bazel/devops/fusionauth:fusionauth
        volumes:
            - type: volume
              source: fa-config
              target: /usr/local/fusionauth/config
        environment:
            - "DATABASE_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/fusionauth?timezone=UTC"
            - "DATABASE_ROOT_USER=${POSTGRES_USER}"
            - "DATABASE_ROOT_PASSWORD=${POSTGRES_PASSWORD}"
            - "DATABASE_USER=fusionauth"
            - "DATABASE_PASSWORD=${FUSIONAUTH_USER_PASSWORD}"
            - "FUSIONAUTH_MEMORY=1G"
            - "FUSIONAUTH_SEARCH_ENGINE_TYPE=database"
        ports:
            - "9011:9011"
        networks:
            c3p0:
                ipv4_address: ${FUSIONAUTH_HOST}
        depends_on:
            - postgres
volumes:
    db-data:
    fa-config:

networks:
    c3p0:
        ipam:
            driver: default
            config:
                - subnet: "172.22.0.0/24"
